---
- name: install fail2ban packages
  apt: 
    pkg: "{{ item }}" 
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - fail2ban
 
- name: update fail2ban jail.local from template
  template:
    src: etc/fail2ban/jail.local
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644
  notify:
    - restart fail2ban

- name: ensure fail2ban service is started and enabled
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - fail2ban
